# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='is_correct',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
