# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-20 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='groups',
            field=models.ManyToManyField(to='registration.StudyGroup'),
        ),
    ]
