# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 19:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_option_is_correct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registration.Faculty'),
        ),
    ]
