# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-22 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_test_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresponse',
            name='marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testresponse',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
    ]
