# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 19:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_auto_20170801_1921'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.CharField(max_length=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name='test',
            name='question',
        ),
        migrations.AlterField(
            model_name='option',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.Question'),
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.Test'),
        ),
    ]
