# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 19:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_auto_20170801_1926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='test',
            new_name='question',
        ),
    ]
