# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 21:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_auto_20170801_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0, 3600)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
