# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 12:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_auto_20170802_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Faculty'),
        ),
    ]
