# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-12 17:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0010_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='question',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
