# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 23:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0015_auto_20170801_1907'),
        ('exams', '0013_auto_20170812_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('U', 'unanswered'), ('R', 'review'), ('L', 'locked'), ('N', 'not_visited')], default='unanswered', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TestResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='registration.Student')),
                ('test', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='exams.Test')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='response',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='exams.TestResponse'),
        ),
        migrations.AddField(
            model_name='answer',
            name='selected_option',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='exams.Option'),
        ),
    ]
