# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0017_auto_20170813_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='status',
            field=models.CharField(choices=[('U', 'unanswered'), ('R', 'review'), ('L', 'locked'), ('N', 'not_visited')], default='not_visited', max_length=20),
        ),
    ]
