# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name_plural': 'Faculty Accounts'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': 'Student Accounts'},
        ),
        migrations.AddField(
            model_name='faculty',
            name='name',
            field=models.CharField(default='empty', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(choices=[('CS', 'Computer Science & Engineering'), ('IT', 'Information Technoology'), ('BT', 'Biotechnology'), ('EC', 'Electronics and Communication Engineering'), ('EE', 'Electrical and Electronics Engineering'), ('ME', 'Mechanical Engineering')], max_length=2),
        ),
    ]
