# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20170729_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('1', '1st'), ('2', '2nd'), ('3', '3rd'), ('4', '4th')], max_length=1)),
                ('branch', models.CharField(choices=[('CS', 'Computer Science & Engineering'), ('IT', 'Information Technology'), ('BT', 'Biotechnology'), ('EC', 'Electronics and Communication Engineering'), ('EE', 'Electrical and Electronics Engineering'), ('ME', 'Mechanical Engineering')], max_length=2)),
                ('number', models.IntegerField()),
            ],
        ),
    ]
