# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 23:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import registration.models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_studygroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='registration.StudyGroup'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studygroup',
            name='number',
            field=registration.models.IntegerRangeField(),
        ),
    ]
