# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 00:12
from __future__ import unicode_literals

from django.db import migrations
import registration.models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_auto_20170729_2333'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studygroup',
            options={'verbose_name_plural': 'Study Groups'},
        ),
        migrations.AlterField(
            model_name='studygroup',
            name='number',
            field=registration.models.IntegerRangeField(unique=True),
        ),
    ]
