# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_auto_20170730_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studygroup',
            name='number',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=2),
        ),
    ]
