# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_auto_20170730_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studygroup',
            name='section',
            field=models.CharField(choices=[('1', 'A'), ('2', 'B')], max_length=2),
        ),
    ]
