# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 01:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_auto_20170730_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='username',
            field=models.CharField(default='test', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='faculty',
            name='department',
            field=models.CharField(choices=[('CS', 'Computer Science & Engineering'), ('IT', 'Information Technology'), ('BT', 'Biotechnology'), ('EC', 'Electronics and Communication Engineering'), ('EE', 'Electrical and Electronics Engineering'), ('ME', 'Mechanical Engineering')], max_length=50),
        ),
    ]
