# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 01:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_auto_20170731_0109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='username',
        ),
    ]
