# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 02:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0012_remove_faculty_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='phone_no',
            field=models.CharField(default='9898989898', max_length=10),
            preserve_default=False,
        ),
    ]
