# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 19:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0014_auto_20170801_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='test',
        ),
        migrations.RemoveField(
            model_name='test',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
